name: Linux Build

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Dependencies
        run: |
          sudo apt-get install -y make
          make test
        continue-on-error: false

      - name: Build for Linux
        run: |
          make build
        continue-on-error: false

      - name: List Build Directory (for Debugging)
        run: ls -R bin

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: template-go-project-linux-amd64
          path: 'bin/template-go-project'
