name: Windows Build

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Dependencies
        run: |
          choco install make -y
          make test
        continue-on-error: false

      - name: Build for Windows
        run: |
          make build PROJ_BINARY=template-go-project.exe
        continue-on-error: false

      - name: List Build Directory (for Debugging)
        run: ls -R bin

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: template-go-project-windows-amd64
          path: 'bin/template-go-project.exe'
